spring:
  application:
    name: wampart

  mongodb:
    uri: ${WARMPERT_MONGODB_URI}


server:
  port: ${PORT:9020}


app:
  security:
    default-password: ${DEFAULT_PASSWORD:12345678}


jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000

Cloudinary:
  cloud_name: ${CLOUDINARY_CLOUD_NAME}
  api_key: ${CLOUDINARY_API_KEY}
  api_secret: ${CLOUDINARY_API_SECRET}


logging:
  level:
    root: INFO
    com:
      wampart: DEBUG
    org:
      springframework:
        data:
          mongodb: DEBUG

kind: Application


twilio:
  account-sid: ${TWILIO_ACCOUNT_SID}
  auth-token: ${TWILIO_AUTH_TOKEN}
  whatsapp-number: +14155238886
  admin-whatsapp-number: "25470750362"